### ISSUE TITLE
Did you try this script?

### ISSUE THREAD

**Issue by cdgtf** [xiadong1994/ca_dmv_appointment#1]
I tried to use this script, but it seems like that I cannot get an appointment after I run it every 2 mins for around one day. I am not sure whether it is true that nobody cancel appointment.

**Comment by xiadong1994** [comment]
Yes I am using this script. 

If you can send requests faster, you may be luckier to find a date. However, recently, approximately one or two weeks ago, DMV updated their anti-spider mechanism so you cannot send request in a bit higher frequency, such as 1 request in 1 minute. Otherwise your requests from this IP will be rejected for a while (I'm not sure how long it will be, but not permanent).

I cannot find a good appointment date these days too. I haven't figured out how to bypass the DMV new defense. Maybe a proxy pool will work. If you have any idea, please tell me.

Thanks.

**Comment by cdgtf** [comment]
Thanks. I will try to figure out whether we can find one solution for this. Thanks for your sharing.
